Repository camaraproject/Commonalities, pull requests merged in 2024-11, with the labels that each got.

#315 Common 'area' data-type
  artifacts/CAMARA_common.yaml
Labels: Spring25, priority

#316 Normalization of error status and code allowed values
  artifacts/CAMARA_common.yaml
  documentation/API-design-guidelines.md
Labels: Spring25, priority

#331 Security and Privacy Considerations for Filtering
  documentation/API-design-guidelines.md
Labels: documentation, Spring25

#333 Clarification on api-name, filenames and servers object
  documentation/API-design-guidelines.md
Labels: documentation, Spring25

#335 Security scheme in CAMARA_common.yaml
  artifacts/CAMARA_common.yaml
Labels: Spring25

#311 Broken DPV link removed, broken link to API Versioning in CAMARA wiki was corrected
  documentation/API-design-guidelines.md
Labels: correction

#324 Update error codes and info.description template for device / phone number identifiers
  documentation/API-design-guidelines.md
Labels: documentation, Spring25

#336 Filtering for boolean
  documentation/API-design-guidelines.md
Labels: documentation, Spring25

#347 Synchronization with Maintenance 0.4 branch
  documentation/API-design-guidelines.md
Labels: correction, Spring25

#343 Align API-Testing-Guidelines with new Enhancements and Alignments in Errors
  documentation/API-Testing-Guidelines.md
Labels: Spring25
