Repository camaraproject/Commonalities, pull requests merged in 2024-12, with the labels that each got.

#329 Enhancements and Alignments in Errors
  artifacts/CAMARA_common.yaml
  documentation/API-design-guidelines.md
Labels: enhancement, Spring25

#351 Error alignments for Event Notifications Artifact
  artifacts/notification-as-cloud-event.yaml
  documentation/API-design-guidelines.md
Labels: correction, Spring25

#342 Release 2.1
  CHANGELOG.md
  README.md
  VERSION.yaml
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  artifacts/notification-as-cloud-event.yaml
Labels: release management

#325 Common artifacts for testing error scenarios for device and phoneNumber
  artifacts/testing/C01-device-errors.feature
  artifacts/testing/C02-phoneNumber-errors.feature
Labels: Spring25

#337 Update spectral rule to handle null values error in example fields
  artifacts/linting_rules/.spectral.yml
Labels: correction
