Repository camaraproject/Commonalities, pull requests merged in 2025-01, with the labels that each got.

#320 Create API-cheatsheet.md
  documentation/API-cheatsheet.md
Labels: documentation, Spring25

#361 Subscriptions and Notifications artifacts errors aligment -enum values-
  artifacts/camara-cloudevents/event-subscription-template.yaml
  artifacts/notification-as-cloud-event.yaml
Labels: enhancement, correction, Spring25

#379 Update support for networkAccessIdentifier in CAMARA_common.yaml
  artifacts/CAMARA_common.yaml
Labels: Spring25

#375 Change guidelines on `x-camara-commonalities` extension field
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/API-design-guidelines.md
Labels: Spring25

#386 Update C01-device-errors.feature
  artifacts/testing/C01-device-errors.feature
  artifacts/testing/C02-phoneNumber-errors.feature
Labels: correction, Spring25

#377 Improve 403 INVALID_TOKEN_CONTEXT scope/description
  documentation/API-design-guidelines.md
Labels: Spring25

#374 Clarification on non-mandatory error statuses, 429 made non-madatory
  documentation/API-design-guidelines.md
Labels: Spring25

#387 Allow zero-length strings in x-correlator header
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/API-design-guidelines.md
Labels: correction, Spring25

#390 Updated message field and description for Error 429
  artifacts/CAMARA_common.yaml
  documentation/API-design-guidelines.md
Labels: documentation, Spring25

#388 Release 2.2
  CHANGELOG.md
  README.md
  VERSION.yaml
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  artifacts/notification-as-cloud-event.yaml
Labels: release management
