Repository camaraproject/Commonalities, pull requests merged in 2025-04, with the labels that each got.

#441 CAMARA API Design Guide document
  documentation/API-design-guidelines.md
  documentation/CAMARA-API-Design-Guide.md
Labels: documentation, Fall25

#429 Remove AUTHENTICATION_REQUIRED error code
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/CAMARA-API-Design-Guide.md
Labels: correction, Fall25

#432 Update `types` property of `Subscription` schema in event-subscription-template.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/CAMARA-API-Event-Subscription-and-Notification-Guide.md
Labels: enhancement, Fall25

#453 Links to CAMARA API Event Subscription and Notification Guide in artifacts
  artifacts/camara-cloudevents/event-subscription-template.yaml
  artifacts/notification-as-cloud-event.yaml
Labels: Fall25
