Repository camaraproject/Commonalities, pull requests merged in 2025-06, with the labels that each got.

#455 Remove IDENTIFIER_MISMATCH error and introduce DeviceResponse object
  artifacts/CAMARA_common.yaml
  documentation/CAMARA-API-Design-Guide.md
Labels: Fall25

#471 Sorting Logic Enhancements in Fall25
  documentation/CAMARA-API-Design-Guide.md
Labels: enhancement, Fall25

#459 Text description aligment for duration format fields
  documentation/CAMARA-API-Design-Guide.md
Labels: enhancement, Fall25

#464 Enhancements Subscription/Notification Architecture for Fall25
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/CAMARA-API-Event-Subscription-and-Notification-Guide.md
Labels: enhancement, Fall25

#477 Clarification on using multiple event types
  artifacts/camara-cloudevents/event-subscription-template.yaml
  documentation/CAMARA-API-Event-Subscription-and-Notification-Guide.md
Labels: Fall25

#480 Gherkin Feature: x-correlator format checking step since Fall25
  artifacts/CAMARA_common.yaml
  artifacts/camara-cloudevents/event-subscription-template.yaml
  artifacts/notification-as-cloud-event.yaml
  documentation/API-Testing-Guidelines.md
Labels: correction

#470 Add event-notification feature file template
  artifacts/camara-cloudevents/event-subscription-template.feature
Labels: Fall25
